# An example of running htsget-rs with Crypt4GH enabled.
# Run with `cargo run -p htsget-axum --features experimental -- --config htsget-config/examples/config-files/c4gh.toml`

ticket_server_addr = "127.0.0.1:8080"
data_server_addr = "127.0.0.1:8081"

[[resolvers]]
regex = ".*"
substitution_string = "$0"

[resolvers.storage]
backend = 'Local'

[resolvers.storage.keys]
location = "Local"
private_key = "data/c4gh/keys/bob.sec" # pragma: allowlist secret
recipient_public_key = "data/c4gh/keys/alice.pub"

# Or, use AWS secrets manager to store keys.
#[resolvers.storage.keys]
#location = "SecretsManager"
#private_key = "htsget/test_c4gh_private_key" # pragma: allowlist secret
#recipient_public_key = "htsget/test_c4gh_public_key"
