# An example of running htsget-rs with Crypt4GH enabled.
# Run with `cargo run -p htsget-axum --features experimental -- --config htsget-config/examples/config-files/c4gh.toml`

ticket_server.addr = "127.0.0.1:8080"
data_server.addr = "127.0.0.1:8081"

[[resolvers]]
regex = ".*"
substitution_string = "$0"

[locations.backend]
kind = "File"

[locations.backend.keys]
kind = "Local"
private = "data/c4gh/keys/bob.sec" # pragma: allowlist secret
public = "data/c4gh/keys/alice.pub"

# Or, use AWS secrets manager to store keys.
#[locations.backend.keys]
#kind = "SecretsManager"
#private = "htsget/test_c4gh_private_key" # pragma: allowlist secret
#public = "htsget/test_c4gh_public_key"
