# An example for a server which uses s3 storage with data located in "bucket".
# Run with `cargo run -p htsget-axum --features s3-storage -- --config htsget-config/examples/config-files/s3_storage.toml`

ticket_server.cors.allow_headers = "All"
ticket_server.cors.allow_methods = "All"
ticket_server.cors.allow_credentials = true
ticket_server.cors.max_age = 300

data_server = "None"

[[locations]]
regex = "^(bucket)/(?P<key>.*)$"
substitution_string = "$key"
backend.kind = "S3"

# Or, set the bucket manually
#backend.kind = "S3"
#backend.bucket = "bucket"
