# An example config file for a TLS data server that uses a local storage backend.
# Run with `cargo run -p htsget-axum -- --config htsget-config/examples/config-files/tls_data_server.toml`

ticket_server.addr = "0.0.0.0:8080"
data_server.addr = "0.0.0.0:8081"
data_server.cors.allow_origins = "All"
data_server.tls.cert = "cert.pem"
data_server.tls.key = "key.pem"

[[locations]]
regex = ".*"
substitution_string = "$0"
backend.kind = "Local"
