# An example config file for a TLS ticket server that uses S3 as a storage backend.
# Run with `cargo run -p htsget-axum --features s3 -- --config htsget-config/examples/config-files/tls_ticket_server.toml`

ticket_server.addr = "0.0.0.0:8080"
ticket_server.cors_allow_origins = "All"
ticket_server.tls.cert = "cert.pem"
ticket_server.tls.key = "key.pem"
data_server.addr = "0.0.0.0:8081"

[[locations]]
regex = ".*"
substitution_string = "$0"
backend.kind = "S3"
backend.bucket = "bucket"
