# An example config file for a TLS data server that uses a local storage backend.
# Run with `cargo run -p htsget-actix -- --config htsget-config/examples/config-files/tls_data_server.toml`

ticket_server_addr = "0.0.0.0:8080"
data_server_addr = "0.0.0.0:8081"
data_server_cors_allow_origins = "All"
data_server_tls.cert = "cert.pem"
data_server_tls.key = "key.pem"

[[resolvers]]
regex = ".*"
substitution_string = "$0"
