# An example for a server which uses url storage with data located at "http://localhost:3000".
# Run with
# `cargo run -p htsget-actix --features url-storage -- --config htsget-config/examples/config-files/url_storage.toml`
# in the project directory.

ticket_server_addr = "0.0.0.0:8080"
ticket_server_cors_allow_origins = "All"

data_server_enabled = false

[[resolvers]]
regex = ".*"
substitution_string = "$0"

[resolvers.storage]
url = "http://localhost:3000"
response_scheme = "http"
