# An example for a server which uses url storage with data located at "http://localhost:3000".
# Run with
# `cargo run -p htsget-axum --features url -- --config htsget-config/examples/config-files/url_storage.toml`
# in the project directory.

ticket_server.addr = "127.0.0.1:8082"
ticket_server.cors.allow_origins = "All"

ticket_server.cert = "cert.pem"
ticket_server.key = "key.pem"

data_server = "None"

[[locations]]
regex = ".*"
substitution_string = "$0"

backend.kind = "Url"
backend.url = "http://127.0.0.1:8081"
backend.response_url = "https://127.0.0.1:8081"
backend.forward_headers = true

# Set client authentication
#backend.tls.key = "key.pem"
#backend.tls.cert = "cert.pem"

# Set root certificates
#backend.tls.root_store = "cert.pem"
