[package]
name = "htsget-test"
version = "0.4.2"
rust-version = "1.65"
authors = ["Marko Malenic <mmalenic1@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Common test functions and utilities used by htsget-rs."
documentation = "https://github.com/umccr/htsget-rs/blob/main/htsget-test/README.md"
homepage = "https://github.com/umccr/htsget-rs/blob/main/htsget-test/README.md"
repository = "https://github.com/umccr/htsget-rs"

[features]
http-tests = [
    "dep:async-trait",
    "dep:http",
    "dep:serde_json",
    "dep:serde",
]
cors-tests = ["http-tests", "dep:htsget-config"]
server-tests = [
    "http-tests",
    "dep:htsget-config",
    "dep:noodles",
    "dep:reqwest",
    "dep:tokio",
    "dep:futures",
    "dep:mime",
    "dep:base64"
]
s3-storage = ["htsget-config?/s3-storage"]
url-storage = ["htsget-config?/url-storage"]
default = []

[dependencies]
# Server tests dependencies
htsget-config = { version = "0.6.0", path = "../htsget-config", default-features = false, optional = true }

noodles = { version = "0.40", optional = true, features = ["async", "bgzf", "vcf"] }

reqwest = { version = "0.11", default-features = false, features = ["json", "blocking", "rustls-tls"], optional = true }
tokio = { version = "1.28", features = ["rt-multi-thread"], optional = true }
futures = { version = "0.3", optional = true }
async-trait = { version = "0.1", optional = true }
http = { version = "0.2", optional = true }
mime = { version = "0.3", optional = true }
serde_json = { version = "1.0", features = ["preserve_order"], optional = true }
serde = { version = "1.0", optional = true }
base64 = { version = "0.21", optional = true }

# Default dependencies
rcgen = "0.10"
