[package]
name = "htsget-test"
version = "0.1.0"
rust-version = "1.60"
authors = ["Marko Malenic <mmalenic1@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Common test functions and utilities used by htsget-rs"
documentation = "https://github.com/umccr/htsget-rs/blob/main/htsget-test/README.md"
homepage = "https://github.com/umccr/htsget-rs/blob/main/htsget-test/README.md"
repository = "https://github.com/umccr/htsget-rs"

[features]
http-tests = [
    "dep:async-trait",
    "dep:http",
    "dep:serde_json",
    "dep:serde",
]
cors-tests = ["http-tests", "dep:htsget-config"]
server-tests = [
    "http-tests",
    "dep:htsget-config",
    "dep:htsget-search",
    "dep:htsget-http",
    "dep:noodles-vcf",
    "dep:noodles-bgzf",
    "dep:reqwest",
    "dep:tokio",
    "dep:futures",
    "dep:mime",
    "dep:base64"
]
s3-storage = ["htsget-config?/s3-storage", "htsget-search?/s3-storage", "htsget-http?/s3-storage"]
default = ["s3-storage"]

[dependencies]
# Server tests dependencies
htsget-http = { version = "0.1.0", path = "../htsget-http", default-features = false, optional = true }
htsget-config = { version = "0.1.0", path = "../htsget-config", default-features = false, optional = true }
htsget-search = { version = "0.1.0", path = "../htsget-search", default-features = false, optional = true }

noodles-vcf = { version = "0.23", features = ["async"], optional = true }
noodles-bgzf = { version = "0.18", features = ["async"], optional = true }

reqwest = { version = "0.11", default-features = false, features = ["json", "blocking", "rustls-tls"], optional = true }
tokio = { version = "1.21", features = ["rt-multi-thread"], optional = true }
futures = { version = "0.3", optional = true }
async-trait = { version = "0.1", optional = true }
http = { version = "0.2", optional = true }
mime = { version = "0.3", optional = true }
serde_json = { version = "1.0", optional = true }
serde = { version = "1.0", optional = true }
base64 = { version = "0.20", optional = true }

# Default dependencies
rcgen = "0.10"
