[package]
name = "htsget-test"
version = "0.5.3"
rust-version = "1.67"
authors = ["Marko Malenic <mmalenic1@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Common test functions and utilities used by htsget-rs."
documentation = "https://github.com/umccr/htsget-rs/blob/main/htsget-test/README.md"
homepage = "https://github.com/umccr/htsget-rs/blob/main/htsget-test/README.md"
repository = "https://github.com/umccr/htsget-rs"

[features]
http-tests = [
    "dep:async-trait",
    "dep:http",
    "dep:serde_json",
    "dep:serde",
    "dep:tokio",
    "dep:htsget-config",
    "dep:noodles",
    "dep:base64",
    "dep:futures",
]
cors-tests = ["http-tests", "dep:htsget-config"]
server-tests = [
    "http-tests",
    "dep:htsget-config",
    "dep:noodles",
    "dep:reqwest",
    "dep:tokio",
    "dep:futures",
    "dep:mime",
    "dep:base64"
]
aws-mocks = [
    "s3-storage",
    "dep:tempfile",
    "dep:aws-sdk-s3",
    "dep:aws-config",
    "dep:aws-credential-types",
    "dep:s3s",
    "dep:s3s-fs",
    "dep:s3s-aws"
]
s3-storage = ["htsget-config?/s3-storage"]
url-storage = ["htsget-config?/url-storage"]
crypt4gh = ["dep:crypt4gh", "dep:async-crypt4gh", "htsget-config?/crypt4gh"]
default = []

[dependencies]
# Server tests dependencies
htsget-config = { version = "0.8.0", path = "../htsget-config", default-features = false, optional = true }

noodles = { version = "0.60", optional = true, features = ["async", "bgzf", "vcf"] }

reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"], optional = true }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
futures = { version = "0.3", optional = true }
async-trait = { version = "0.1", optional = true }
http = { version = "0.2", optional = true }
mime = { version = "0.3", optional = true }
serde_json = { version = "1.0", features = ["preserve_order"], optional = true }
serde = { version = "1", optional = true }
base64 = { version = "0.21", optional = true }

tempfile = { version = "3.3", optional = true }
aws-sdk-s3 = { version = "0.30", features = ["test-util"], optional = true }
aws-config = { version = "0.56", optional = true }
aws-credential-types = { version = "0.56", features = ["test-util"], optional = true }
s3s = { version = "0.7", optional = true }
s3s-fs = { version = "0.7", optional = true }
s3s-aws = { version = "0.7", optional = true }

crypt4gh = { version = "0.4", git = "https://github.com/umccr/crypt4gh-rust", branch = "fix_rust_crypto_et_al", optional = true }
async-crypt4gh = { version = "0.1.0", path = "../async-crypt4gh", optional = true }

# Default dependencies
rcgen = "0.11"
