[package]
name = "htsget-http"
version = "0.4.10"
rust-version = "1.70"
authors = ["Daniel del Castillo de la Rosa <delcastillodelarosadaniel@gmail.com>", "Marko Malenic <mmalenic1@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Crate for handling HTTP in htsget-rs."
documentation = "https://github.com/umccr/htsget-rs/blob/main/htsget-http/README.md"
homepage = "https://github.com/umccr/htsget-rs/blob/main/htsget-http/README.md"
repository = "https://github.com/umccr/htsget-rs"

[features]
s3-storage = ["htsget-config/s3-storage", "htsget-search/s3-storage", "htsget-test/s3-storage"]
url-storage = ["htsget-config/url-storage", "htsget-search/url-storage", "htsget-test/url-storage"]
crypt4gh = ["htsget-config/crypt4gh", "htsget-search/crypt4gh", "htsget-test/crypt4gh"]
default = []

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
http = "0.2"
htsget-search = { version = "0.6.4", path = "../htsget-search", default-features = false }
htsget-config = { version = "0.7.1", path = "../htsget-config", default-features = false }
htsget-test = { version = "0.5.2", path = "../htsget-test", default-features = false }
futures = { version = "0.3" }
tokio = { version = "1.29", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
