
[package]
name = "htsget-http"
version = "0.1.0"
authors = ["Daniel del Castillo de la Rosa <delcastillodelarosadaniel@gmail.com>"]
edition = "2018"

[dependencies]

actix-web = "3"
thiserror = "~1.0"
serde = "1"
htsget-search = { path = "../htsget-search" }