[package]
name = "htsget-http"
version = "0.1.1"
rust-version = "1.64"
authors = ["Daniel del Castillo de la Rosa <delcastillodelarosadaniel@gmail.com>", "Marko Malenic <mmalenic1@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Framework independent code for handling HTTP in htsget-rs"
documentation = "https://github.com/umccr/htsget-rs/blob/main/htsget-http/README.md"
homepage = "https://github.com/umccr/htsget-rs/blob/main/htsget-http/README.md"
repository = "https://github.com/umccr/htsget-rs"

[features]
s3-storage = ["htsget-config/s3-storage", "htsget-search/s3-storage", "htsget-test/s3-storage"]
default = ["s3-storage"]

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
http = "0.2"
htsget-search = { version = "0.1.1", path = "../htsget-search", default-features = false }
htsget-config = { version = "0.1.1", path = "../htsget-config", default-features = false }
futures = { version = "0.3" }
tokio = { version = "1.21", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"

[dev-dependencies]
htsget-test = { version = "0.1.1", path = "../htsget-test", default-features = false }
