[workspace]
members = [
    "htsget-config",
    "htsget-actix",
    "htsget-http",
    "htsget-lambda",
    "htsget-search",
    "htsget-test",
    "htsget-benchmarks",
]

# Flamegraphs require debuginfo for symbol names.
[profile.bench]
debug = true
