[workspace]
members = [
    "htsget-search",
    "htsget-http-core",
    "htsget-http-actix",
    "htsget-devtools",
    "htsget-id-resolver",
    #[cfg(feature = "aws")]
    "htsget-http-aws-lambda"
]