
[package]
name = "htsget-http-actix"
version = "0.1.0"
authors = ["Daniel del Castillo de la Rosa <delcastillodelarosadaniel@gmail.com>"]
edition = "2018"

[dependencies]

actix-web = "3"
htsget-http-core = { path = "../htsget-http-core" }
htsget-search = { path = "../htsget-search" }