[package]
name = "htsget-http-actix"
version = "0.1.0"
authors = ["Daniel del Castillo de la Rosa <delcastillodelarosadaniel@gmail.com>"]
edition = "2018"

[features]
default = ["async", "htsget-search/default", "htsget-http-core/default"]
async = ["tokio", "futures", "htsget-search/async", "htsget-http-core/async"]

[dependencies]
actix-web = "3"
envy = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures-util = { version = "0.3.5", default-features = false }
htsget-http-core = { path = "../htsget-http-core" }
htsget-search = { path = "../htsget-search" }
htsget-id-resolver = { path = "../htsget-id-resolver" }
futures = { version = "0.3.16", optional = true }
tokio = { version = "1.9.0", features = ["full"], optional = true }
