
[package]
name = "htsget-http-actix"
version = "0.1.0"
authors = ["Daniel del Castillo de la Rosa <delcastillodelarosadaniel@gmail.com>"]
edition = "2018"

[[bin]]
name = "htsget-http-actix"
bench = false

[dependencies]

actix-web = "3"
actix-files = "0.5"
envy = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures-util = { version = "0.3.5", default-features = false }
htsget-http-core = { path = "../htsget-http-core" }
htsget-search = { path = "../htsget-search" }

[dev-dependencies]
criterion = "0.3"
reqwest = { version = "0.11", features = ["blocking", "json"] }

[[bench]]
name = "request-benchmark"
harness = false