
[package]
name = "htsget-http-actix"
version = "0.1.0"
authors = ["Daniel del Castillo de la Rosa <delcastillodelarosadaniel@gmail.com>"]
edition = "2018"

[dependencies]

actix-web = "3"
envy = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures-util = { version = "0.3.5", default-features = false }
htsget-http-core = { path = "../htsget-http-core" }
htsget-search = { path = "../htsget-search" }