
[package]
name = "htsget-actix"
version = "0.1.0"
authors = ["Daniel del Castillo de la Rosa <delcastillodelarosadaniel@gmail.com>"]
edition = "2018"

[dependencies]

actix-web = "3"
htsget-http = { path = "../htsget-http" }
htsget-search = { path = "../htsget-search" }