
[package]
name = "htsget-http-core"
version = "0.1.0"
authors = ["Daniel del Castillo de la Rosa <delcastillodelarosadaniel@gmail.com>"]
edition = "2018"

[dependencies]

thiserror = "~1.0"
serde = { version = "1", features = ["derive"] }
htsget-search = { path = "../htsget-search" }