[package]
name = "htsget-config"
version = "0.1.0"
authors = ["Daniel del Castillo de la Rosa <delcastillodelarosadaniel@gmail.com>"]
edition = "2021"

[dependencies]

regex = "1.5.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_regex = "1.1.0"