[package]
name = "htsget-config"
version = "0.8.0"
rust-version = "1.70"
authors = ["Daniel del Castillo de la Rosa <delcastillodelarosadaniel@gmail.com>", "Marko Malenic <mmalenic1@gmail.com>"]
edition = "2021"
description = "Used to configure htsget-rs by using a config file or reading environment variables."
license = "MIT"
documentation = "https://github.com/umccr/htsget-rs/blob/main/htsget-config/README.md"
homepage = "https://github.com/umccr/htsget-rs/blob/main/htsget-config/README.md"
repository = "https://github.com/umccr/htsget-rs"

[features]
s3-storage = []
url-storage = ["hyper"]
crypt4gh = ["dep:async-crypt4gh", "dep:crypt4gh"]
default = []

[dependencies]
thiserror = "1.0"
async-trait = "0.1"
noodles = { version = "0.50", features = ["core"] }
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.2"
serde_regex = "1.1"
regex = "1.8"
figment = { version = "0.10", features = ["env", "toml"] }
clap = { version = "4.3", features = ["derive", "env", "cargo"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter", "ansi", "json"] }
toml = "0.7"
http = "0.2"
http-serde = "1.1"
rustls-pemfile = "1.0"
rustls = "0.21"
rustls-native-certs = "0.6"
hyper-rustls = { version = "0.24", features = ["rustls-native-certs", "http2", "http1"] }

hyper = { version = "0.14", features = ["http1", "http2", "client"], optional = true }

async-crypt4gh = { version = "0.1.0", path = "../async-crypt4gh", default-features = false, optional = true }
crypt4gh = { version = "0.4", optional = true }

[dev-dependencies]
serde_json = "1.0"
figment = { version = "0.10", features = ["test"] }
tokio = { version = "1.29", features = ["macros", "rt-multi-thread"] }
tempfile = "3.7"
rcgen = "0.11"
