[package]
name = "htsget-search"
version = "0.1.0"
authors = ["Christian Perez Llamas <chrispz@gmail.com>", "Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2018"

[dependencies]
thiserror = "~1.0"

noodles = { version = "0.2.0", features = ["bam", "bcf", "bgzf", "cram", "csi", "sam", "tabix", "vcf"] }

[dev-dependencies]
tempfile = "3.2.0"