[package]
name = "htsget-search"
version = "0.1.0"
authors = ["Christian Perez Llamas <chrispz@gmail.com>", "Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2018"

[features]
default = ["async"]
async = ["tokio", "futures"]
aws = ["s3-server", "aws-sdk-s3", "aws-config"]

[dependencies]
bytes = "1.1.0"
regex = "1"
async-trait = "0.1.50"
thiserror = "~1.0"
#[cfg(feature = "aws")]
anyhow = "1.0.44" # TODO: s3_server requires this, but it should be easily removable?
tokio = { version = "1.9.0", features = ["full"], optional = true }
futures = { version = "0.3.16", optional = true }
htsget-id-resolver = { path = "../htsget-id-resolver"}

# AWS deps
#[cfg(feature = "aws")]
s3-server = { version = "0.1.0", optional = true }
#[cfg(feature = "aws")]
aws-sdk-s3 = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.20-alpha", package = "aws-sdk-s3", optional = true }
#[cfg(feature = "aws")]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.20-alpha", package = "aws-config", optional = true }
#[cfg(feature = "aws")]
lazy_static = "1.4.0"
hyper = "0.14.13"
tracing = "0.1.28"
tracing-error = "0.1.2"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.2.18" }

# Bioinformatics deps
noodles = { git = "https://github.com/zaeleus/noodles", features = ["bgzf", "bam", "bcf", "cram", "csi", "sam", "tabix", "vcf"] }
noodles-bgzf = { git = "https://github.com/zaeleus/noodles", features = ['async'] }
noodles-bam = { git = "https://github.com/zaeleus/noodles", features = ['async'] }
noodles-bcf = { git = "https://github.com/zaeleus/noodles", features = ['async'] }
noodles-cram = { git = "https://github.com/zaeleus/noodles", features = ['async'] }
noodles-csi = { git = "https://github.com/zaeleus/noodles", features = ['async'] }
noodles-tabix = { git = "https://github.com/zaeleus/noodles", features = ['async'] }
noodles-vcf = { git = "https://github.com/zaeleus/noodles", features = ['async'] }

[dev-dependencies]
tempfile = "3.2.0"
#[cfg(feature = "aws")]
s3-server = "0.1.0"