[package]
name = "htsget-search"
version = "0.1.0"
authors = ["Christian Perez Llamas <chrispz@gmail.com>", "Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2018"

[dependencies]
thiserror = "~1.0"

# noodles = { version = "0.1.0", git = "https://github.com/zaeleus/noodles.git", features = ["bgzf, sam, bam, vcf, tabix"] }

# noodles-core =  { path = "../../noodles/noodles-core" }
# noodles-bgzf =  { path = "../../noodles/noodles-bgzf" }
# noodles-bam =   { path = "../../noodles/noodles-bam" }
# noodles-sam =   { path = "../../noodles/noodles-sam" }
# noodles-vcf =   { path = "../../noodles/noodles-vcf" }
# noodles-tabix = { path = "../../noodles/noodles-tabix" }

noodles-core =  { git = "https://github.com/zaeleus/noodles.git", rev = "2f23ab7a864573e3175e2b5c249a4afe470cd73c" }
noodles-bgzf =  { git = "https://github.com/zaeleus/noodles.git", rev = "2f23ab7a864573e3175e2b5c249a4afe470cd73c" }
noodles-bam =   { git = "https://github.com/zaeleus/noodles.git", rev = "2f23ab7a864573e3175e2b5c249a4afe470cd73c" }
noodles-cram =  { git = "https://github.com/zaeleus/noodles.git", rev = "2f23ab7a864573e3175e2b5c249a4afe470cd73c" }
noodles-sam =   { git = "https://github.com/zaeleus/noodles.git", rev = "2f23ab7a864573e3175e2b5c249a4afe470cd73c" }
noodles-vcf =   { git = "https://github.com/zaeleus/noodles.git", rev = "2f23ab7a864573e3175e2b5c249a4afe470cd73c" }
noodles-bcf =   { git = "https://github.com/zaeleus/noodles.git", rev = "2f23ab7a864573e3175e2b5c249a4afe470cd73c" }
noodles-tabix = { git = "https://github.com/zaeleus/noodles.git", rev = "2f23ab7a864573e3175e2b5c249a4afe470cd73c" }
noodles-csi = { git = "https://github.com/zaeleus/noodles.git", rev = "2f23ab7a864573e3175e2b5c249a4afe470cd73c" }


[dev-dependencies]
tempfile = "3.2.0"