[package]
name = "htsget-search"
version = "0.1.0"
authors = ["Christian Perez Llamas <chrispz@gmail.com>", "Marko Malenic <mmalenic1@gmail.com>", "Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2018"

[features]
default = ["async"]
async = ["tokio", "futures"]

[dependencies]
async-trait = "0.1.50"
thiserror = "~1.0"
tokio = { version = "1.12.0", features = ["full"], optional = true }
futures = { version = "0.3.16", optional = true }
htsget-id-resolver = { path = "../htsget-id-resolver"}

noodles = { version = "0.11.0", features = ["bgzf", "bam", "bcf", "cram", "csi", "sam", "tabix", "vcf"] }

noodles-bgzf = { version = "0.4.0", features = ['async'] }
noodles-bam = { version = "0.7.0", features = ['async'] }
noodles-bcf = { version = "0.6.1", features = ['async'] }
noodles-cram = { version = "0.7.0", features = ['async'] }
noodles-csi = { version = "0.3.0", features = ['async'] }
noodles-tabix = { version = "0.6.1", features = ['async'] }
noodles-vcf = { version = "0.8.0", features = ['async'] }

# noodles = { git = "https://github.com/zaeleus/noodles", features = ["bgzf", "bam", "bcf", "cram", "csi", "sam", "tabix", "vcf"] }

# noodles-bgzf = { git = "https://github.com/zaeleus/noodles", features = ['async'] }
# noodles-bam = { git = "https://github.com/zaeleus/noodles", features = ['async'] }
# noodles-bcf = { git = "https://github.com/zaeleus/noodles", features = ['async'] }
# noodles-cram = { git = "https://github.com/zaeleus/noodles", features = ['async'] }
# noodles-csi = { git = "https://github.com/zaeleus/noodles", features = ['async'] }
# noodles-tabix = { git = "https://github.com/zaeleus/noodles", features = ['async'] }
# noodles-vcf = { git = "https://github.com/zaeleus/noodles", features = ['async'] }

[dev-dependencies]
tempfile = "3.2.0"