[package]
name = "htsget-search"
version = "0.1.0"
authors = ["Christian Perez Llamas <christian.perez@adevinta.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "~1.0"

# rust-htslib = "~0.36"

noodles = { git = "https://github.com/zaeleus/noodles.git" }
noodles-bgzf = { git = "https://github.com/zaeleus/noodles.git" }
noodles-bam = { git = "https://github.com/zaeleus/noodles.git" }
noodles-sam = { git = "https://github.com/zaeleus/noodles.git" }

[dev-dependencies]
tempfile = "3.2.0"