[package]
name = "htsget-search"
version = "0.1.0"
authors = ["Christian Perez Llamas <chrispz@gmail.com>", "Marko Malenic <mmalenic1@gmail.com>", "Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2021"

[features]
default = ["async"]
async = ["tokio", "futures"]

[dependencies]
async-trait = "0.1.52"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"], optional = true }
futures = { version = "0.3.21", optional = true }
htsget-id-resolver = { path = "../htsget-id-resolver"}

noodles = { git = "https://github.com/zaeleus/noodles", branch = "master", features = ["bgzf", "bam", "bcf", "cram", "csi", "sam", "tabix", "vcf"] }

#noodles-bgzf = { version = "0.8.0", features = ['async'] }
noodles-bam = { git = "https://github.com/zaeleus/noodles", branch = "master", features = ["async"] }
noodles-bcf = { git = "https://github.com/zaeleus/noodles", branch = "master", features = ["async"] }
noodles-cram = { git = "https://github.com/zaeleus/noodles", branch = "master", features = ["async"] }
#noodles-csi = { version = "0.4.3", features = ['async'] }
#noodles-tabix = { version = "0.7.3", features = ['async'] }
noodles-vcf = { git = "https://github.com/zaeleus/noodles", branch = "master", features = ["async"] }

[dev-dependencies]
tempfile = "3.2.0"