[package]
name = "htsget-search"
version = "0.1.0"
authors = ["Christian Perez Llamas <chrispz@gmail.com>", "Marko Malenic <mmalenic1@gmail.com>", "Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2021"

[features]
default = ["async"]
async = ["tokio", "futures"]

[dependencies]
async-trait = "0.1.50"
thiserror = "~1.0"
tokio = { version = "1.16.1", features = ["full"], optional = true }
futures = { version = "0.3.16", optional = true }
htsget-id-resolver = { path = "../htsget-id-resolver"}

noodles = { version = "0.18.0", features = ["bgzf", "bam", "bcf", "cram", "csi", "sam", "tabix", "vcf"] }

noodles-bgzf = { version = "0.8.0", features = ['async'] }
noodles-bam = { version = "0.14.0", features = ['async'] }
noodles-bcf = { version = "0.12.0", features = ['async'] }
noodles-cram = { version = "0.11.0", features = ['async'] }
noodles-csi = { version = "0.4.3", features = ['async'] }
noodles-tabix = { version = "0.7.3", features = ['async'] }
noodles-vcf = { version = "0.13.0", features = ['async'] }

[dev-dependencies]
tempfile = "3.2.0"