[package]
name = "htsget-search"
version = "0.1.0"
authors = ["Christian Perez Llamas <chrispz@gmail.com>", "Marko Malenic <mmalenic1@gmail.com>", "Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2021"

[features]
default = ["async"]
async = ["tokio", "futures"]
aws = ["aws-sdk-s3", "aws-config"]

[dependencies]
async-trait = "0.1.52"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"], optional = true }
tokio-util = { version = "0.7.0", features = ["io", "compat"] }
async-stream = "0.3.3"
futures = { version = "0.3.21", optional = true }
htsget-id-resolver = { path = "../htsget-id-resolver"}

noodles = { git = "https://github.com/zaeleus/noodles", branch = "master", features = ["core", "bgzf", "bam", "bcf", "cram", "csi", "sam", "tabix", "vcf"] }
noodles-bam = { git = "https://github.com/zaeleus/noodles", branch = "master", features = ["async"] }
noodles-bcf = { git = "https://github.com/zaeleus/noodles", branch = "master", features = ["async"] }
noodles-cram = { git = "https://github.com/zaeleus/noodles", branch = "master", features = ["async"] }
noodles-vcf = { git = "https://github.com/zaeleus/noodles", branch = "master", features = ["async"] }

#[cfg(feature = "aws")]
bytes = "1.1.0"
#[cfg(feature = "aws")]
aws-sdk-s3 = { version = "0.9.0", optional = true }
#[cfg(feature = "aws")]
aws-config = { version = "0.9.0", optional = true }

[dev-dependencies]
tempfile = "3.2.0"
#[cfg(feature = "aws")]
hyper = "0.14.17"
#[cfg(feature = "aws")]
anyhow = "1.0.56"
#[cfg(feature = "aws")]
s3-server = "0.1.0"
#[cfg(feature = "aws")]
http = "0.2.6"
#[cfg(feature = "aws")]
aws-types = { version = "0.9.0", features = ["hardcoded-credentials"] }