[package]
name = "htsget-search"
version = "0.1.0"
authors = ["Christian Perez Llamas <chrispz@gmail.com>", "Marko Malenic <mmalenic1@gmail.com>", "Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2021"

[features]
s3-storage = ["dep:bytes", "dep:aws-sdk-s3", "dep:aws-config", "htsget-config/s3-storage", "htsget-test-utils/s3-storage"]
default = ["s3-storage"]

[dependencies]
# Axum server dependencies.
hyper = "0.14"
tower-http = { version = "0.3", features = ["trace"] }
axum = "0.5.1"
axum-extra = { version = "0.2.1", features = ["spa"] }
rustls-pemfile = "0.3"
tower = { version = "0.4", features = ["make"] }
futures-util = "0.3"
tokio-rustls = "0.23"

async-trait = "0.1"
thiserror = "1.0"
tokio = { version = "1.17", features = ["full"] }
tokio-util = { version = "0.7", features = ["io", "compat"] }
futures = { version = "0.3" }
htsget-config = { path = "../htsget-config", default-features = false }
tracing = "0.1"
base64 = "0.13"

noodles = { version = "0.24", features = ["core", "bgzf", "bam", "bcf", "cram", "csi", "sam", "tabix", "vcf"] }
noodles-bam = { version = "0.19", features = ["async"] }
noodles-bcf = { version = "0.13", features = ["async"] }
noodles-cram = { version = "0.16", features = ["async"] }
noodles-vcf = { version = "0.16", features = ["async"] }

# Aws S3 storage dependencies.
bytes = { version = "1.1", optional = true }
aws-sdk-s3 = { version = "0.9", optional = true }
aws-config = { version = "0.9", optional = true }

[dev-dependencies]
htsget-test-utils = { path = "../htsget-test-utils", default-features = false }
tempfile = "3.3"
data-url = "0.1"

# Aws S3 storage dependencies.
anyhow = "1.0"
s3-server = "0.2"
http = "0.2"
aws-types = { version = "0.9", features = ["hardcoded-credentials"] }

# Axum server dependencies
hyper-tls = "0.5"

criterion = { version = "0.3", features = ["async_tokio"] }

[[bench]]
name = "search-benchmarks"
harness = false
path = "benches/search_benchmarks.rs"