[package]
name = "htsget-search"
version = "0.6.6"
rust-version = "1.65"
authors = ["Christian Perez Llamas <chrispz@gmail.com>", "Marko Malenic <mmalenic1@gmail.com>", "Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2021"
description = "The primary mechanism by which htsget-rs interacts with, and processes bioinformatics files. It does this by using noodles to query files and their indices."
license = "MIT"
documentation = "https://github.com/umccr/htsget-rs/blob/main/htsget-search/README.md"
homepage = "https://github.com/umccr/htsget-rs/blob/main/htsget-search/README.md"
repository = "https://github.com/umccr/htsget-rs"

[features]
s3-storage = [
    "dep:aws-sdk-s3",
    "dep:aws-config",
    "dep:bytes",
    "htsget-config/s3-storage",
    "htsget-test/s3-storage",
    "htsget-test/aws-mocks"
]
url-storage = [
    "dep:bytes",
    "dep:hyper-rustls",
    "dep:mockall",
    "dep:mockall_double",
    "dep:pin-project",
    "hyper/client",
    "htsget-config/url-storage",
    "htsget-test/url-storage"
]
crypt4gh = [
    "dep:async-crypt4gh",
    "dep:crypt4gh",
    "htsget-config/crypt4gh",
    "htsget-test/crypt4gh"
]
default = []

[dependencies]
# Axum server
url = "2.4"
hyper = { version = "0.14", features = ["http1", "http2", "server"] }
tower-http = { version = "0.4", features = ["trace", "cors", "fs"] }
http = "0.2"
axum = "0.6"
rustls-pemfile = "1.0"
tower = { version = "0.4", features = ["make"] }

# Async
tokio-rustls = "0.24"
tokio = { version = "1.29", features = ["macros", "rt-multi-thread"] }
tokio-util = { version = "0.7", features = ["io", "compat"] }
futures = { version = "0.3" }
futures-util = "0.3"
async-trait = "0.1"

# Noodles
noodles = { version = "0.65", features = ["async", "core", "bgzf", "bam", "bcf", "cram", "csi", "sam", "tabix", "vcf"] }

# Amazon S3
bytes = { version = "1.4", optional = true }
aws-sdk-s3 = { version = "0.34", optional = true }
aws-config = { version = "0.56", optional = true }

# Url storage
hyper-rustls = { version = "0.24", features = ["rustls-native-certs", "http2", "http1"], optional = true }
crypt4gh = { version = "0.4", git = "https://github.com/EGA-archive/crypt4gh-rust", optional = true }
async-crypt4gh = { version = "0.1.0", path = "../async-crypt4gh", optional = true }
pin-project = { version = "1.1", optional = true }
mockall = { version = "0.9", optional = true }
mockall_double = { version = "0.3", optional = true }

# Error control, tracing, config
thiserror = "1.0"
htsget-config = { version = "0.8.1", path = "../htsget-config", default-features = false }
htsget-test = { version = "0.5.4", path = "../htsget-test", features = ["http"], default-features = false }
tracing = "0.1"
base64 = "0.21"
serde = "1.0"

reqwest = { version = "0.11", features = ["rustls-tls", "stream"], default-features = false }

[dev-dependencies]
tempfile = "3.6"
data-url = "0.3"
walkdir = "2.5"

criterion = { version = "0.5", features = ["async_tokio"] }

[[bench]]
name = "search-benchmarks"
harness = false
path = "benches/search_benchmarks.rs"
