[package]
name = "htsget-search"
version = "0.1.0"
authors = ["Christian Perez Llamas <christian.perez@adevinta.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "~1.0"

# noodles = { version = "0.1.0", git = "https://github.com/zaeleus/noodles.git", features = ["bgzf, sam, bam, vcf, tabix"] }

noodles-core= { path = "../../noodles/noodles-core" } #git = "https://github.com/zaeleus/noodles.git" }
noodles-bgzf = { path = "../../noodles/noodles-bgzf" } #git = "https://github.com/zaeleus/noodles.git" }
noodles-bam = { path = "../../noodles/noodles-bam" } #git = "https://github.com/zaeleus/noodles.git" }
noodles-sam = { path = "../../noodles/noodles-sam" } #git = "https://github.com/zaeleus/noodles.git" }
noodles-vcf = { path = "../../noodles/noodles-vcf" } #git = "https://github.com/zaeleus/noodles.git" }
noodles-tabix = { path = "../../noodles/noodles-tabix" } #git = "https://github.com/zaeleus/noodles.git" }

[dev-dependencies]
tempfile = "3.2.0"