[package]
name = "htsget-search"
version = "0.1.0"
authors = ["Christian Perez Llamas <chrispz@gmail.com>", "Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2018"

[dependencies]
async-trait = "0.1.50"
thiserror = "~1.0"
tokio = { version = "1.9.0", features = ["full"] }
tokio-stream = "0.1"
futures = "0.3.16"

noodles = { version = "0.5.0", features = ["bgzf", "bam", "bcf", "cram", "csi", "sam", "tabix", "vcf"] }

noodles-bgzf = { version = "0.3.0", features = ['async'] }
noodles-bam = { version = "0.3.0", features = ['async'] }
noodles-bcf = { version = "0.4.0", features = ['async'] }
noodles-tabix = { version = "0.5.0", features = ['async'] }
noodles-vcf = { version = "0.4.0", features = ['async'] }

[dev-dependencies]
tempfile = "3.2.0"