[package]
name = "htsget-search"
version = "0.1.0"
authors = ["Christian Perez Llamas <chrispz@gmail.com>", "Marko Malenic <mmalenic1@gmail.com>", "Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2021"

[features]
default = ["s3-storage", "gds-storage"]
s3-storage = ["bytes", "aws-sdk-s3", "aws-config"]
gds-storage = ["ica-gds", "dirs", "url", "serde", "serde_yaml"]

[dependencies]
# Illumina GDS Storage backend credentials and url parsing
dirs = { version = "4.0", optional = true }
url = { version = "2.2", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_yaml = { version = "0.8", optional = true }

# Axum server dependencies.
hyper = "0.14"
axum = "0.5.1"
axum-extra = { version = "0.2.1", features = ["spa"] }
rustls-pemfile = "0.3"
tower = { version = "0.4", features = ["make"] }
futures-util = "0.3"
tokio-rustls = "0.23"

async-trait = "0.1"
thiserror = "1.0"
tokio = { version = "1.17", features = ["full"] }
tokio-util = { version = "0.7", features = ["io", "compat"] }
futures = { version = "0.3" }
htsget-config = { path = "../htsget-config" }
tracing = "0.1"

noodles = { version = "0.21", features = ["core", "bgzf", "bam", "bcf", "cram", "csi", "sam", "tabix", "vcf"] }
noodles-bam = { version = "0.17", features = ["async"] }
noodles-bcf = { version = "0.13", features = ["async"] }
noodles-cram = { version = "0.14", features = ["async"] }
noodles-vcf = { version = "0.15", features = ["async"] }

# Aws S3 storage dependencies.
bytes = { version = "1.1", optional = true }
aws-sdk-s3 = { version = "0.9", optional = true }
aws-config = { version = "0.9", optional = true }

# Illumina GDS storage
#ica-gds = { path = "../../ica-rs/gds", optional = true}
ica-gds = { git = "https://github.com/umccr-illumina/ica-rs", optional = true }

[dev-dependencies]
tempfile = "3.3"

# Aws S3 storage dependencies.
anyhow = "1.0"
s3-server = "0.2"
http = "0.2"
aws-types = { version = "0.9", features = ["hardcoded-credentials"] }

# Axum server dependencies
rcgen = "0.9"
hyper-tls = "0.5"
