[package]
name = "htsget-search"
version = "0.1.0"
authors = ["Christian Perez Llamas <chrispz@gmail.com>", "Marko Malenic <mmalenic1@gmail.com>", "Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2021"

[features]
default = ["s3-storage"]
s3-storage = ["aws-sdk-s3", "aws-config"]

[dependencies]
# Axum server dependencies.
hyper = "0.14"
axum = "0.5.1"
axum-extra = { version = "0.2.1", features = ["spa"] }
rustls-pemfile = "0.3"
tokio-tls = "0.3"
tower = { version = "0.4", features = ["make"] }
futures-util = "0.3"
tokio-rustls = "0.23"

async-trait = "0.1"
thiserror = "1.0"
tokio = { version = "1.17", features = ["full"] }
tokio-util = { version = "0.7", features = ["io", "compat"] }
futures = { version = "0.3" }
htsget-config = { path = "../htsget-config" }

noodles = { version = "0.21", features = ["core", "bgzf", "bam", "bcf", "cram", "csi", "sam", "tabix", "vcf"] }
noodles-bam = { version = "0.17", features = ["async"] }
noodles-bcf = { version = "0.13", features = ["async"] }
noodles-cram = { version = "0.14", features = ["async"] }
noodles-vcf = { version = "0.15", features = ["async"] }

#[cfg(feature = "aws")]
bytes = "1.1"
#[cfg(feature = "aws")]
aws-sdk-s3 = { version = "0.9", optional = true }
#[cfg(feature = "aws")]
aws-config = { version = "0.9", optional = true }

[dev-dependencies]
tempfile = "3.3"
#[cfg(feature = "aws")]
hyper = "0.14"
#[cfg(feature = "aws")]
anyhow = "1.0"
#[cfg(feature = "aws")]
s3-server = "0.2"
#[cfg(feature = "aws")]
http = "0.2"
#[cfg(feature = "aws")]
aws-types = { version = "0.9", features = ["hardcoded-credentials"] }

# Axum server dependencies
rcgen = "0.9"
hyper-tls = "0.5"
