[package]
name = "htsget-lambda"
version = "0.4.16"
rust-version = "1.74"
authors = ["Marko Malenic <mmalenic1@gmail.com>", "Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2021"
license = "MIT"
description = "A cloud-based instance of htsget-rs, using AWS Lambda, which can be configured using htsget-config."
documentation = "https://github.com/umccr/htsget-rs/blob/main/htsget-lambda/README.md"
homepage = "https://github.com/umccr/htsget-rs/blob/main/htsget-lambda/README.md"
repository = "https://github.com/umccr/htsget-rs"

[features]
s3-storage = ["htsget-config/s3-storage", "htsget-search/s3-storage", "htsget-http/s3-storage", "htsget-storage/s3-storage", "htsget-test/s3-storage"]
url-storage = ["htsget-config/url-storage", "htsget-search/url-storage", "htsget-http/url-storage", "htsget-storage/url-storage", "htsget-test/url-storage"]
default = []

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.5", features = ["cors"] }
lambda_http = { version = "0.11" }
lambda_runtime = { version = "0.11" }
serde = { version = "1" }
serde_json = "1"
mime = "0.3"
regex = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
bytes = "1"

htsget-config = { version = "0.10.0", path = "../htsget-config", default-features = false }
htsget-search = { version = "0.7.1", path = "../htsget-search", default-features = false }
htsget-http = { version = "0.4.14", path = "../htsget-http", default-features = false }
htsget-test = { version = "0.6.1", path = "../htsget-test", features = ["http"], default-features = false }
htsget-storage = { version = "0.1.0", path = "../htsget-storage", default-features = false }

[dev-dependencies]
async-trait = "0.1"
query_map = { version = "0.7", features = ["url-query"] }
tempfile = "3"
