name: tests

on: [push]

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust }}
            override: true
            components: rustfmt, clippy
      - name: Cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-cache3-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-cargo-cache3-
      # - name: Cargo fmt
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: fmt
      # - name: Clippy
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: clippy
      #     args: -- -D warnings
      # - name: Build all features
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --all-targets --all-features
      # - name: Build no default features
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --all-targets --no-default-features
      # - name: Build s3-storage feature
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --all-targets --features s3-storage
      # - name: Run cargo test
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: test
      #     args: --all-features
      # Benchmarking
      - name: Install cargo-criterion
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-criterion
            # JSON on stdout, bencher (human readable) results on stderr
      - name: Timestamp
        run: export BENCH_TIMESTAMP=$(date +'%Y-%m-%d-%s')
      # - name: Run requests benchmarks
      #   #run: cargo criterion --bench request-benchmarks --message-format=json -- LIGHT 1> requests-benchmarks-${BENCH_TIMESTAMP}.json
      #   run: cargo criterion --bench request-benchmarks --message-format=json -- LIGHT 1> requests-benchmarks.json
      - name: Run search benchmarks
        #run: cargo criterion --bench search-benchmarks --message-format=json -- LIGHT 1> search-benchmarks-${BENCH_TIMESTAMP}.json
        run: cargo criterion --bench search-benchmarks --message-format=json -- LIGHT | tee output.txt
      - name: Where is output.txt
        run: pwd && ls -alh && find .. -iname 'output.txt'
      # - name: Store requests benchmark result
      #   uses: benchmark-action/github-action-benchmark@v1
      #   with:
      #     tool: 'cargo'
      #     # Where the output from the benchmark tool is stored
      #     #output-file-path: requests-benchmarks-${BENCH_TIMESTAMP}.json
      #     output-file-path: ${{ github.repository }}/requests-benchmarks.json
      #     # Where the previous data file is stored
      #     #external-data-json-path: ./cache/requests-benchmarks-${BENCH_TIMESTAMP}.json
      #     external-data-json-path: ./benchmarks/requests-benchmarks.json
      #     fail-on-alert: false
      - name: Store search benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Search benchmark
          tool: 'cargo'
          output-file-path: ../output.txt
          #external-data-json-path: search-benchmarks.json
          fail-on-alert: false
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.HTSGET_RS_BENCHMARKS_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
      # - name: Setup Pages
      #   uses: actions/configure-pages@v2
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v1
      #   with:
      #     path: 'search-benchmarks.json'
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v1