name: tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    uses: umccr/reusable-github-actions/.github/workflows/rust-check.yaml@master
  test:
    needs: check
    uses: umccr/reusable-github-actions/.github/workflows/rust-test.yaml@master
  benchmark:
    uses: umccr/reusable-github-actions/.github/workflows/rust-benchmark.yaml@master
    needs: check

  # TODO: Release process needs to be parametrized properly for reuse
  # release:
  #   uses: umccr/reusable-github-actions/.github/workflows/rust-release.yaml@master

  # TODO: Release please requires special syntax on commit messages, see: https://www.conventionalcommits.org/en/v1.0.0/
  # release:
  #   needs: check
  #   - name: Create release PR
  #     uses: GoogleCloudPlatform/release-please-action@v3
  #       id: release_main
  #       with:
  #         release-type: rust
  #         package-name: htsget-search
  #         bump-minor-pre-major: true
  #         monorepo-tags: true
  #         path: "."

  # TODO: Explore how to publish the other crates in htsget-rs workspace
  #   - name: Publish htsget-search
  #       if: ${{ steps.release_sys.outputs.release_created }}
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: publish
  #         args: --manifest-path htsget-search/Cargo.toml --token ${{ secrets.CRATES_IO_TOKEN }}
  #
  # TODO: Publish docker containers too, as suggested by @victorskl
  # Use a minimal Rust container for that, i.e: https://ectobit.com/blog/rust-container-image-buildkit-buildx/