name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    uses: umccr/reusable-github-actions/rust-check.yaml@master
  test:
    uses: umccr/reusable-github-actions/rust-test.yaml@master
  benchmark:
    uses: umccr/reusable-github-actions/rust-benchmark.yaml@master