name: tests

on: [push]

env:
    AWS_ACCESS_KEY_ID: "FOO"
    AWS_SECRET_ACCESS_KEY: "BAR"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust }}
            override: true
            components: rustfmt, clippy

      - name: Install cargo-lambda
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-lambda

      - uses: Swatinem/rust-cache@v1
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: Build all features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --all-features

      - name: Build no default features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --no-default-features

      - name: Build s3-storage feature
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --features s3-storage

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --all-features
