name: Run Rust tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust }}
            override: true
            components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Run cargo clippy with no default features
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-default-features

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Run cargo test with all features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - name: Run cargo test with no default features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features
