name: Run Rust tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@master
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt, clippy
      - name: Cargo rustfmt force-install? # See: https://github.com/chris-zen/htsget-mvp/pull/6/checks?check_run_id=2286913153#step:4:14
        run: rustup component add rustfmt --toolchain 1.51.0-x86_64-unknown-linux-gnu
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run cargo fmt
        run: cargo fmt
      - name: Run cargo clippy
        run: cargo clippy
      - name: Run tests
        run: cargo test
