name: tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    uses: umccr/reusable-github-actions/.github/workflows/rust-check.yaml@master
  test:
    needs: check
    uses: umccr/reusable-github-actions/.github/workflows/rust-test.yaml@master
  benchmark:
    uses: umccr/reusable-github-actions/.github/workflows/rust-benchmark.yaml@master
    needs: check
  release:
    uses: umccr/reusable-github-actions/.github/workflows/rust-release.yaml@master
    needs: ["check", "test"]