name: benchmarks

on:
  push:
    branches:
      - main

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust }}
            override: true
            components: rustfmt, clippy
      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-criterion
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-criterion
      - name: Run search benchmarks
        run: cargo criterion --bench search-benchmarks --message-format=json -- LIGHT 1> search-benchmarks-output.json
      - name: Store search benchmark result
        uses: brainstorm/github-action-benchmark@cargo-criterion-v3
        with:
          name: Search benchmark
          tool: 'cargo-criterion'
          output-file-path: search-benchmarks-output.json
          native-benchmark-data-dir-path: target/criterion
          fail-on-alert: false
          github-token: ${{ secrets.HTSGET_RS_BENCHMARKS_TOKEN }}
          auto-push: true
