name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        id: toolchain
        with:
          toolchain: ${{ matrix.rust }}
      - run: rustup override set ${{ steps.toolchain.outputs.name }}
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: build-cache
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Build all features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --all-features
      - name: Build no default features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --no-default-features
      - name: Build s3-storage
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --features s3-storage
      - name: Build url-storage
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --features url-storage
