name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            # Todo: remove this when clippy introduces https://github.com/rust-lang/rust-clippy/pull/10865 in nightly or stable.
            toolchain: 1.69
            # toolchain: ${{ matrix.rust }}
            override: true
            components: rustfmt, clippy
      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Build all features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --all-features
      - name: Build no default features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --no-default-features
      - name: Build s3-storage
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --features s3-storage
      - name: Build url-storage
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --features url-storage
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features  -- -D warnings
      - name: Run cargo tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - name: Run cargo tests no default features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features
